version: '3.8'

services:
  # Servicio principal de la aplicación (Producción)
  registro-fisico:
    image: sergioscardigno82/registro-fisico:latest
    container_name: registro-fisico-app
    ports:
      - "5000:5000"
    volumes:
      # Montar directorio de datos para persistencia
      - ./data:/app/instance
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - registro-fisico-network

networks:
  registro-fisico-network:
    driver: bridge