version: '3.8'

services:
  # Servicio de producción optimizado
  registro-fisico:
    image: tu-usuario/registro-fisico:latest
    container_name: registro-fisico-prod
    ports:
      - "80:5000"  # Puerto 80 para producción
    volumes:
      - ./data:/app/instance
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

# Volúmenes para persistencia
volumes:
  data:
    driver: local
